FROM node:8.1.0-alpine

ENV HOME=/opt/helloworld/
RUN mkdir $HOME

COPY src/package.json src/npm-shrinkwrap.json $HOME

WORKDIR $HOME
RUN npm install

RUN npm install --global gulp-cli
COPY src/. $HOME/

RUN ["gulp","bundle"] 