version: '3.1'

services:

  helloworld:
    image: "${AUTHOR}/${NAME}:${TAG}"
    environment:
      - APP_PORT=${CONTAINER_PORT}
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - "node.labels.env==${ENV}"