FROM node:8.1.0-alpine

ENV APP_HOME=/opt/app/
RUN mkdir $APP_HOME

COPY src/. $APP_HOME/

WORKDIR $APP_HOME

RUN npm install && \
    npm install --global gulp-cli && \
    npm test

RUN ["gulp","bundle"] 