version: '3.1'

services:

  helloworld:
    image: "${AUTHOR}/${NAME}:${TAG}"
    environment:
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - "node.labels.env==${ENV}"